<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Re: mod_python 3.3.1 bug report
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Re%3A%20mod_python%203.3.1%20bug%20report&In-Reply-To=485b313b.281d640a.0664.65beSMTPIN_ADDED%40mx.google.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="025372.html">
   <LINK REL="Next"  HREF="025374.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Re: mod_python 3.3.1 bug report</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Graham Dumpleton</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Re%3A%20mod_python%203.3.1%20bug%20report&In-Reply-To=485b313b.281d640a.0664.65beSMTPIN_ADDED%40mx.google.com"
       TITLE="[mod_python] Re: mod_python 3.3.1 bug report">graham.dumpleton at gmail.com
       </A><BR>
    <I>Fri Jun 20 00:28:42 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="025372.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
        <LI>Next message: <A HREF="025374.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25373">[ date ]</a>
              <a href="thread.html#25373">[ thread ]</a>
              <a href="subject.html#25373">[ subject ]</a>
              <a href="author.html#25373">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Huh, that doesn't quite make sense. Can you replace:

  PythonHandler mptest

with:

  PythonHandler mod_python.testhandler

This will use an inbuilt test handler within mod_python and return a
lot of debug if it works.

If that still doesn't work, can only suggest uninstalling both Python
and mod_python and reinstalling, making sure they are installed as
account with Administrator privileges for good measure.

Graham

2008/6/20 Mike Landis &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mlandis001 at comcast.net</A>&gt;:
&gt;<i> Graham,
</I>&gt;<i>
</I>&gt;<i> I'm sorry, 'line' is defined by the for loop, so you wanted all three lines
</I>&gt;<i> within the for loop, as follows...
</I>&gt;<i>            for line in tb:
</I>&gt;<i>                                import sys
</I>&gt;<i>                                print &gt;&gt; sys.stderr, repr(line[:-1])
</I>&gt;<i>                                sys.stderr.flush()
</I>&gt;<i>                                log_error(line[:-1], flags)
</I>&gt;<i>
</I>&gt;<i> that produces:
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [notice] mod_python (pid=3332,
</I>&gt;<i> interpreter='localhost'): Importing module 'D:\\htdocs\\Python\\mptest.py'
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] mod_python (pid=3332,
</I>&gt;<i> interpreter='localhost', phase='PythonHandler', handler='mptest'):
</I>&gt;<i> Application error
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] ServerName:
</I>&gt;<i> 'localhost'
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] DocumentRoot:
</I>&gt;<i> 'D:/htdocs'
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] URI:
</I>&gt;<i> '/Python/mptest.py'
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] Location: None
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] Directory:
</I>&gt;<i> 'D:/htdocs/Python/'
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] Filename:
</I>&gt;<i> 'D:/htdocs/Python/mptest.py'
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] PathInfo: ''
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] Traceback (most recent
</I>&gt;<i> call last):
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 1537, in HandlerDispatch\n    default=default_handler, arg=req,
</I>&gt;<i> silent=hlist.silent)
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 1202, in _process_target\n    module = import_module(module_name, path=path)
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 296, in import_module\n    log, import_path)
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1]   File
</I>&gt;<i> &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;, line
</I>&gt;<i> 680, in import_module\n    execfile(file, module.__dict__)
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>  File &quot;D:\Programs\Python25\lib\site-packages\mod_python\importer.py&quot;, line
</I>&gt;<i> 1784, in ReportError
</I>&gt;<i>    import sys
</I>&gt;<i> TypeError: argument 1 must be string without null bytes or None, not str
</I>&gt;<i> [Fri Jun 20 00:24:18 2008] [error] [client 127.0.0.1] python_handler:
</I>&gt;<i> Dispatch() returned non-integer.
</I>&gt;<i>
</I>&gt;<i> -Mike
</I>&gt;<i> At 11:49 PM 6/19/2008, Graham Dumpleton wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Instead of repr(), try str() then. Also try:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  line[:-1].encode('UTF-8')
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I think.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> You might add at same level of indent in that loop:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  import sys
</I>&gt;&gt;<i>  print &gt;&gt; sys.stderr, repr(line[:-1])
</I>&gt;&gt;<i>  sys.stderr.flush()
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> This should hopefully flush out to Apache logs and by pass the
</I>&gt;&gt;<i> mod_python error log function.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> If still no luck, there may be some issue with Python installation, not
</I>&gt;&gt;<i> sure.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Graham
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> 2008/6/20 Mike Landis &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mlandis001 at comcast.net</A>&gt;:
</I>&gt;&gt;<i> &gt; Graham,
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; This result looks similar (if not identical).
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; -Mike
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [notice] mod_python (pid=3332,
</I>&gt;&gt;<i> &gt; interpreter='localhost'): Importing module
</I>&gt;&gt;<i> &gt; 'D:\\htdocs\\Python\\mptest.py'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] mod_python
</I>&gt;&gt;<i> &gt; (pid=3332,
</I>&gt;&gt;<i> &gt; interpreter='localhost', phase='PythonHandler', handler='mptest'):
</I>&gt;&gt;<i> &gt; Application error
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] ServerName:
</I>&gt;&gt;<i> &gt; 'localhost'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] DocumentRoot:
</I>&gt;&gt;<i> &gt; 'D:/htdocs'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] URI:
</I>&gt;&gt;<i> &gt; '/Python/mptest.py'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Location: None
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Directory:
</I>&gt;&gt;<i> &gt; 'D:/htdocs/Python/'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Filename:
</I>&gt;&gt;<i> &gt; 'D:/htdocs/Python/mptest.py'
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] PathInfo: ''
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] Traceback (most
</I>&gt;&gt;<i> &gt; recent
</I>&gt;&gt;<i> &gt; call last):
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 1537, in HandlerDispatch\n    default=default_handler, arg=req,
</I>&gt;&gt;<i> &gt; silent=hlist.silent)
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 1202, in _process_target\n    module = import_module(module_name,
</I>&gt;&gt;<i> &gt; path=path)
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 296, in import_module\n    log, import_path)
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 680, in import_module\n    execfile(file, module.__dict__)
</I>&gt;&gt;<i> &gt; Traceback (most recent call last):
</I>&gt;&gt;<i> &gt;  File &quot;D:\Programs\Python25\lib\site-packages\mod_python\importer.py&quot;,
</I>&gt;&gt;<i> &gt; line
</I>&gt;&gt;<i> &gt; 1784, in ReportError
</I>&gt;&gt;<i> &gt;    log_error(repr(line[:-1]), flags)                           # was:
</I>&gt;&gt;<i> &gt;  log_error(line[:-1], flags)
</I>&gt;&gt;<i> &gt; TypeError: argument 1 must be string without null bytes or None, not str
</I>&gt;&gt;<i> &gt; [Thu Jun 19 23:41:58 2008] [error] [client 127.0.0.1] python_handler:
</I>&gt;&gt;<i> &gt; Dispatch() returned non-integer.
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt; At 11:19 PM 6/19/2008, Graham Dumpleton wrote:
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; Please use reply-all and keep followups on mailing list.
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; Anyway, read message wrong first time. It isn't log_error() in your
</I>&gt;&gt;<i> &gt;&gt; code which is problem, but code in mod_python used to display error
</I>&gt;&gt;<i> &gt;&gt; tracebacks. In particular:
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt;            tb = traceback.format_exception(etype, evalue, etb)
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt;            for line in tb:
</I>&gt;&gt;<i> &gt;&gt;                log_error(line[:-1], flags)
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; I can only image that somehow a Unicode character string has gotten
</I>&gt;&gt;<i> &gt;&gt; into traceback message from Python.
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; What I suggest you do is modify the importer.py in mod_python
</I>&gt;&gt;<i> &gt;&gt; installed source so that that log_error() call reads:
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt;                log_error(repr(line[:-1]), flags)
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; That should show you true error which is first occurring. Unicode
</I>&gt;&gt;<i> &gt;&gt; strings shouldn't be an issue then as are converting it all to
</I>&gt;&gt;<i> &gt;&gt; displayable latin.
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; Please don't though just fix the error if in your code if obvious,
</I>&gt;&gt;<i> &gt;&gt; instead post the resultant error traceback to list so can see how
</I>&gt;&gt;<i> &gt;&gt; unicode string is getting into traceback.
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; Graham
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; 2008/6/20 Mike Landis &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mlandis001 at comcast.net</A>&gt;:
</I>&gt;&gt;<i> &gt;&gt; &gt; Graham,
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; The results look identical to me... (see immediately below)
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; -Mike
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [notice] mod_python (pid=3332,
</I>&gt;&gt;<i> &gt;&gt; &gt; interpreter='localhost'): Importing module
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:\\htdocs\\Python\\mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] mod_python
</I>&gt;&gt;<i> &gt;&gt; &gt; (pid=3332,
</I>&gt;&gt;<i> &gt;&gt; &gt; interpreter='localhost', phase='PythonHandler', handler='mptest'):
</I>&gt;&gt;<i> &gt;&gt; &gt; Application error
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] ServerName:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'localhost'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] DocumentRoot:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:/htdocs'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] URI:
</I>&gt;&gt;<i> &gt;&gt; &gt; '/Python/mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Location: None
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Directory:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:/htdocs/Python/'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Filename:
</I>&gt;&gt;<i> &gt;&gt; &gt; 'D:/htdocs/Python/mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] PathInfo: ''
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] Traceback (most
</I>&gt;&gt;<i> &gt;&gt; &gt; recent
</I>&gt;&gt;<i> &gt;&gt; &gt; call last):
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line
</I>&gt;&gt;<i> &gt;&gt; &gt; 1537, in HandlerDispatch\n    default=default_handler, arg=req,
</I>&gt;&gt;<i> &gt;&gt; &gt; silent=hlist.silent)
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line
</I>&gt;&gt;<i> &gt;&gt; &gt; 1202, in _process_target\n    module = import_module(module_name,
</I>&gt;&gt;<i> &gt;&gt; &gt; path=path)
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line
</I>&gt;&gt;<i> &gt;&gt; &gt; 296, in import_module\n    log, import_path)
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line
</I>&gt;&gt;<i> &gt;&gt; &gt; 680, in import_module\n    execfile(file, module.__dict__)
</I>&gt;&gt;<i> &gt;&gt; &gt; Traceback (most recent call last):
</I>&gt;&gt;<i> &gt;&gt; &gt;  File
</I>&gt;&gt;<i> &gt;&gt; &gt; &quot;D:\Programs\Python25\lib\site-packages\mod_python\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt; line
</I>&gt;&gt;<i> &gt;&gt; &gt; 1784, in ReportError
</I>&gt;&gt;<i> &gt;&gt; &gt;    log_error(line[:-1], flags)
</I>&gt;&gt;<i> &gt;&gt; &gt; TypeError: argument 1 must be string without null bytes or None, not
</I>&gt;&gt;<i> &gt;&gt; &gt; str
</I>&gt;&gt;<i> &gt;&gt; &gt; [Thu Jun 19 22:42:54 2008] [error] [client 127.0.0.1] python_handler:
</I>&gt;&gt;<i> &gt;&gt; &gt; Dispatch() returned non-integer.
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt; ==========================================================================
</I>&gt;&gt;<i> &gt;&gt; &gt; At 09:33 PM 6/19/2008, you wrote:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; What happens when you use:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;  from mod_python import apache
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;  apache.log_error('handler')
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; instead?
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; Graham
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; 2008/6/16 Mike Landis &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">mlandis001 at comcast.net</A>&gt;:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 32 bit Windows Vista, Apache 2.2.8, mod_python 3.3.1, python
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 2.5.2.2
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; (r252:60911)
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; I received a 500 error from Apache httpd while attempting to get
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; mod_python working on Windows Vista.  Following are entries from
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; error.log, httpd.conf, and the Python source (mptest.py) used as a
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; test
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; case.  The error
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; occurs within importer.py (part of the mod_pyton site-package).
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; Apache httpd error log:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [notice] mod_python (pid=3708,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; interpreter='localhost'): Importing module
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 'D:\\htdocs\\Python\\mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] mod_python
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; (pid=3708, interpreter='localhost', phase='PythonHandler',
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; handler='mptest'): Application error
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] ServerName:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 'localhost'
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; DocumentRoot:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 'D:/htdocs'
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] URI:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; '/Python/mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Location:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; None
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Directory:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 'D:/htdocs/Python/'
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Filename:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 'D:/htdocs/Python/mptest.py'
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] PathInfo: ''
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1] Traceback
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; (most
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; recent call last):
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; line 1537, in HandlerDispatch\n default=default_handler, arg=req,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; silent=hlist.silent)
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; line 1202, in _process_target\n module =
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; import_module(module_name,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; path=path)
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; line 296, in import_module\n log, import_path)
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]   File
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; &quot;D:\\Programs\\Python25\\lib\\site-packages\\mod_python\\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; line 680, in import_module\n execfile(file, module.__dict__)
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; Traceback (most recent call last): File
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; &quot;D:\Programs\Python25\lib\site-packages\mod_python\importer.py&quot;,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; line 1784, in ReportError log_error(line[:-1], flags)
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; TypeError: argument 1 must be string without null bytes or None,
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; not
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; str
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; [Sat Jun 14 16:22:29 2008] [error] [client 127.0.0.1]
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; python_handler:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; Dispatch() returned non-integer.
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; --------------------------------------------------------------------------------
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; httpd.conf entries:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; LoadModule python_module modules/mod_python.so
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; &lt;Directory D:\htdocs\Python&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; AddHandler      mod_python .py
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;        PythonHandler   mptest
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;        PythonDebug
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; On
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; &lt;/Directory&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; --------------------------------------------------------------------------------
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; Python source (in mptest.py):
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; from mod_python import apache
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; def handler(req):
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;         req.log_error('handler')
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;         req.content_type =
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt; 'text/plain'
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;         req.write('HelloWorld\n')
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;         return apache.OK
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; No virus found in this incoming message.
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; Checked by AVG.
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; Version: 8.0.100 / Virus Database: 270.4.0/1509 - Release Date:
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; 6/19/2008
</I>&gt;&gt;<i> &gt;&gt; &gt;&gt; 8:00 AM
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt; &gt;
</I>&gt;&gt;<i> &gt;&gt;
</I>&gt;&gt;<i> &gt;&gt; No virus found in this incoming message.
</I>&gt;&gt;<i> &gt;&gt; Checked by AVG.
</I>&gt;&gt;<i> &gt;&gt; Version: 8.0.100 / Virus Database: 270.4.0/1509 - Release Date:
</I>&gt;&gt;<i> &gt;&gt; 6/19/2008
</I>&gt;&gt;<i> &gt;&gt; 8:00 AM
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i> &gt;
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> No virus found in this incoming message.
</I>&gt;&gt;<i> Checked by AVG.
</I>&gt;&gt;<i> Version: 8.0.100 / Virus Database: 270.4.0/1509 - Release Date: 6/19/2008
</I>&gt;&gt;<i> 8:00 AM
</I>&gt;<i>
</I>&gt;<i>
</I></PRE>




<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="025372.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
	<LI>Next message: <A HREF="025374.html">[mod_python] Re: mod_python 3.3.1 bug report
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25373">[ date ]</a>
              <a href="thread.html#25373">[ thread ]</a>
              <a href="subject.html#25373">[ subject ]</a>
              <a href="author.html#25373">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
