<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] &quot;Cannot re-init internal module exceptions&quot;
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20%22Cannot%20re-init%20internal%20module%20exceptions%22&In-Reply-To=15153.63148.824452.424254%40cymru.basistech.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="011963.html">
   <LINK REL="Next"  HREF="011964.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] &quot;Cannot re-init internal module exceptions&quot;</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Sam Brauer</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20%22Cannot%20re-init%20internal%20module%20exceptions%22&In-Reply-To=15153.63148.824452.424254%40cymru.basistech.com"
       TITLE="[mod_python] &quot;Cannot re-init internal module exceptions&quot;">sam at webslingerZ.com
       </A><BR>
    <I>Thu Jun 21 13:00:37 EST 2001</I>
    <P><UL>
        <LI>Previous message: <A HREF="011963.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
        <LI>Next message: <A HREF="011964.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11966">[ date ]</a>
              <a href="thread.html#11966">[ thread ]</a>
              <a href="subject.html#11966">[ subject ]</a>
              <a href="author.html#11966">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>When I encountered this in some of my code, I simply removed the &quot;import
exceptions&quot; line and it worked fine.
So try commenting that line out in
$ocal/lib/python2.0/site-packages/ahts/Plex/Errors.py

You will probably need to restart apache to see if it works.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sam Brauer : Systems Programmer : <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">sam at webslingerZ.com</A>

On Thu, 21 Jun 2001, Tom Emerson wrote:

&gt;<i> Greetings.
</I>&gt;<i>
</I>&gt;<i> I'm attempting to get mod_python working with the AHTS template engine
</I>&gt;<i> (<A HREF="http://ahts.sourceforge.net">http://ahts.sourceforge.net</A>) but am not having much luck. In
</I>&gt;<i> particular, I get the following error in the server error log (the
</I>&gt;<i> full backtrace is below):
</I>&gt;<i>
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/Errors.py&quot;, line 9, in ?
</I>&gt;<i>     import exceptions
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex: ImportError: Cannot re-init internal module exceptions
</I>&gt;<i>
</I>&gt;<i> This is running in the following configuration:
</I>&gt;<i>
</I>&gt;<i> Apache/1.3.19 (Unix) PHP/4.0.4pl1 mod_python/2.7.2 Python/2.0 configured
</I>&gt;<i>
</I>&gt;<i> Anyone have an idea what is happening here? Any ideas on ameliorating this problem?
</I>&gt;<i>
</I>&gt;<i> TIA,
</I>&gt;<i>
</I>&gt;<i>     -tree
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex: Traceback (most recent call last):
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/mod_python/apache.py&quot;, line 176, in Dispatch
</I>&gt;<i>     module = import_module(module_name, _req)
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/mod_python/apache.py&quot;, line 334, in import_module
</I>&gt;<i>     module = imp.load_module(mname, f, p, d)
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/opt/www/htdocs/chinlex.py&quot;, line 2, in ?
</I>&gt;<i>     import MySQLdb, StringIO, ahts
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/__init__.py&quot;, line 33, in ?
</I>&gt;<i>     from utility import *
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/utility.py&quot;, line 29, in ?
</I>&gt;<i>     import writer
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/writer.py&quot;, line 33, in ?
</I>&gt;<i>     from parser import TemplateParser
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/parser.py&quot;, line 33, in ?
</I>&gt;<i>     from scanner import TemplateScanner
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/scanner.py&quot;, line 33, in ?
</I>&gt;<i>     from Plex import *
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/__init__.py&quot;, line 34, in ?
</I>&gt;<i>     from Lexicons import Lexicon, State
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/Lexicons.py&quot;, line 13, in ?
</I>&gt;<i>     import Errors
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex:   File &quot;/usr/local/lib/python2.0/site-packages/ahts/Plex/Errors.py&quot;, line 9, in ?
</I>&gt;<i>     import exceptions
</I>&gt;<i> [Thu Jun 21 09:59:33 2001] [error] PythonHandler chinlex: ImportError: Cannot re-init internal module exceptions
</I>&gt;<i>
</I>&gt;<i> --
</I>&gt;<i> Tom Emerson                                          Basis Technology Corp.
</I>&gt;<i> Sr. Sinostringologist                              <A HREF="http://www.basistech.com">http://www.basistech.com</A>
</I>&gt;<i>   &quot;Beware the lollipop of mediocrity: lick it once and you suck forever&quot;
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mod_python mailing list
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;<i> <A HREF="http://www.modpython.org/mailman/listinfo/mod_python">http://www.modpython.org/mailman/listinfo/mod_python</A>
</I>&gt;<i>
</I>

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="011963.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
	<LI>Next message: <A HREF="011964.html">[mod_python] &quot;Cannot re-init internal module exceptions&quot;
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11966">[ date ]</a>
              <a href="thread.html#11966">[ thread ]</a>
              <a href="subject.html#11966">[ subject ]</a>
              <a href="author.html#11966">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="DISABLEhttp://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
