<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] 2.7.8: os.error no longer == OSError
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%202.7.8%3A%20os.error%20no%20longer%20%3D%3D%20OSError&In-Reply-To=200307210629.QAA06995%40lightning.itga.com.au">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="013990.html">
   <LINK REL="Next"  HREF="013991.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] 2.7.8: os.error no longer == OSError</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Gregory (Grisha) Trubetskoy</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%202.7.8%3A%20os.error%20no%20longer%20%3D%3D%20OSError&In-Reply-To=200307210629.QAA06995%40lightning.itga.com.au"
       TITLE="[mod_python] 2.7.8: os.error no longer == OSError">grisha at modpython.org
       </A><BR>
    <I>Mon Jul 21 10:47:15 EST 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="013990.html">[mod_python] 2.7.8: os.error no longer == OSError
</A></li>
        <LI>Next message: <A HREF="013991.html">[mod_python] 2.7.8: import exceptions -&gt; os.error no longer ==
	OSError 
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13993">[ date ]</a>
              <a href="thread.html#13993">[ thread ]</a>
              <a href="subject.html#13993">[ subject ]</a>
              <a href="author.html#13993">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>

On Mon, 21 Jul 2003, Gregory Bond wrote:

&gt;<i> I've got
</I>&gt;<i> 	Apache/1.3.27 (Unix) mod_python/2.7.8 Python/2.1.1 configured
</I>
[snip]

I think it's the same problem as the one causing this:
<A HREF="http://www.modpython.org/FAQ/faqw.py?req=all#5.4">http://www.modpython.org/FAQ/faqw.py?req=all#5.4</A>

Try upgrading to Python 2.2.3, I'm almost certain it will fix this.

(I'd upgrade to Apache 2.0.x and mod_python 3.0.3 too if that's an option)

Grisha
</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="013990.html">[mod_python] 2.7.8: os.error no longer == OSError
</A></li>
	<LI>Next message: <A HREF="013991.html">[mod_python] 2.7.8: import exceptions -&gt; os.error no longer ==
	OSError 
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13993">[ date ]</a>
              <a href="thread.html#13993">[ thread ]</a>
              <a href="subject.html#13993">[ subject ]</a>
              <a href="author.html#13993">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
