<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] mod_python calls the wrong python executable
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%20calls%20the%20wrong%20python%20executable&In-Reply-To=44BE0966.2050905%40cs.caltech.edu">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="021625.html">
   <LINK REL="Next"  HREF="021628.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] mod_python calls the wrong python executable</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Graham Dumpleton</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%20calls%20the%20wrong%20python%20executable&In-Reply-To=44BE0966.2050905%40cs.caltech.edu"
       TITLE="[mod_python] mod_python calls the wrong python executable">grahamd at dscpl.com.au
       </A><BR>
    <I>Wed Jul 19 06:55:54 EDT 2006</I>
    <P><UL>
        <LI>Previous message: <A HREF="021625.html">[mod_python] Talk on what is coming in mod_python 3.3.
</A></li>
        <LI>Next message: <A HREF="021628.html">[mod_python] Difference between run the web service standalone
	and via mod_python
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#21626">[ date ]</a>
              <a href="thread.html#21626">[ thread ]</a>
              <a href="subject.html#21626">[ subject ]</a>
              <a href="author.html#21626">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
On 19/07/2006, at 8:28 PM, mvanier wrote:

&gt;<i> OK, I figured it out thanks to your hint.  What I hadn't realized  
</I>&gt;<i> (or had forgotten) is that apache has to run as root (at least  
</I>&gt;<i> initially), and my compiled-from-source python wasn't in the root  
</I>&gt;<i> path.  As it turned out, the root path includes /usr/local/bin so I  
</I>&gt;<i> added a symlink to my python from there and everything works.  Woo  
</I>&gt;<i> hoo!
</I>&gt;<i>
</I>&gt;<i> Would it be feasible to have a PythonExecutable httpd.conf  
</I>&gt;<i> directive to deal with this problem more explicitly?  I'm still not  
</I>&gt;<i> clear on how mod_python tells apache that it's supposed to be using  
</I>&gt;<i> the &quot;python&quot; program to execute python code
</I>
Not necessarily that simple. The manner in which the Python libraries
determine where to look is quite complicated. See:

   Modules/getpath.c

in Python source code. Thus, although you could try and implement a
directive to tell it where to look, you have to get it to use your value
somehow. I haven't looked at it properly, but you may be able to have
the directive trigger the setting of the PYTHONHOME environment
variable to achieve it.

I have deferred trying to implement such a thing in the past as we  
weren't
able to understand what was happening. This was the point of adding the
extra debug output in new versions. Based on what we see from cases like
yours we can decide whether we do need such a directive as PythonHome
or equivalent.

Graham

&gt;<i> Mike
</I>&gt;<i>
</I>&gt;<i> Graham Dumpleton wrote:
</I>&gt;&gt;<i> On 19/07/2006, at 6:30 PM, mvanier wrote:
</I>&gt;&gt;&gt;<i> I'm trying to run mod_python using the latest mod_python snapshot  
</I>&gt;&gt;&gt;<i> with apache 2.2 (compiled from source) on Debian Linux.  I've run  
</I>&gt;&gt;&gt;<i> into a strange error: when I try to run a python script through  
</I>&gt;&gt;&gt;<i> the server, the wrong python executable gets called.  Here's the  
</I>&gt;&gt;&gt;<i> apache error log:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> [Wed Jul 19 01:21:25 2006] [error] make_obcallback: could not  
</I>&gt;&gt;&gt;<i> import mod_python.apache.\n
</I>&gt;&gt;&gt;<i> ImportError: No module named mod_python.apache
</I>&gt;&gt;&gt;<i> [Wed Jul 19 01:21:25 2006] [error] make_obcallback: Python path  
</I>&gt;&gt;&gt;<i> being used &quot;['/usr/lib/python24.zip', '/usr/lib/python2.4', '/usr/ 
</I>&gt;&gt;&gt;<i> lib/python2.4/plat-linux2', '/usr/lib/python2.4/lib-tk', '/usr/ 
</I>&gt;&gt;&gt;<i> lib/python2.4/lib-dynload', '/usr/local/lib/python2.4/site- 
</I>&gt;&gt;&gt;<i> packages', '/usr/lib/python2.4/site-packages', '/usr/lib/ 
</I>&gt;&gt;&gt;<i> python2.4/site-packages/PIL', '/var/lib/python-support/ 
</I>&gt;&gt;&gt;<i> python2.4', '/usr/lib/site-python']&quot;.
</I>&gt;&gt;&gt;<i> [Wed Jul 19 01:21:25 2006] [error] get_interpreter: no  
</I>&gt;&gt;&gt;<i> interpreter callback found.
</I>&gt;&gt;&gt;<i> [Wed Jul 19 01:21:25 2006] [error] [client 127.0.0.1]  
</I>&gt;&gt;&gt;<i> python_handler: Can't get/create interpreter.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> The sys.path of this python interpreter is the one that would  
</I>&gt;&gt;&gt;<i> exist if /usr/bin/python2.4 (which was installed by Debian) was  
</I>&gt;&gt;&gt;<i> called instead of the correct one, which (in my case) is /usr/ 
</I>&gt;&gt;&gt;<i> local/packages/python/bin/python (which I compiled and installed  
</I>&gt;&gt;&gt;<i> myself from source).  I specified this executable when I  
</I>&gt;&gt;&gt;<i> configured mod_python (using the --with-python option).  For some  
</I>&gt;&gt;&gt;<i> reason, though, it isn't getting used.  Any ideas would be  
</I>&gt;&gt;&gt;<i> appreciated.
</I>&gt;&gt;<i> At least you triggered the new debug output specifically put into  
</I>&gt;&gt;<i> mod_python
</I>&gt;&gt;<i> 3.2.9/3.3 to help debug this sort of problem.
</I>&gt;&gt;<i> Anyway, try ensuring that you have &quot;/usr/local/paclages/python/ 
</I>&gt;&gt;<i> bin&quot; first in the
</I>&gt;&gt;<i> PATH environment variable of the user that Apache is run as. If  
</I>&gt;&gt;<i> you don't and
</I>&gt;&gt;<i> when Python is initialised in the context of mod_python, it finds  
</I>&gt;&gt;<i> evidence first
</I>&gt;&gt;<i> of Python being installed in some other location instead of the  
</I>&gt;&gt;<i> one you want,
</I>&gt;&gt;<i> then it will setup sys.path based on the location of that other  
</I>&gt;&gt;<i> version of Python
</I>&gt;&gt;<i> and thus not look where you actually installed the Python  
</I>&gt;&gt;<i> components of
</I>&gt;&gt;<i> mod_python.
</I>&gt;&gt;<i> BTW, does /usr/bin/python or /usr/lib/python2.4 actually exist.
</I>&gt;&gt;<i> Graham
</I>
</PRE>






<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="021625.html">[mod_python] Talk on what is coming in mod_python 3.3.
</A></li>
	<LI>Next message: <A HREF="021628.html">[mod_python] Difference between run the web service standalone
	and via mod_python
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#21626">[ date ]</a>
              <a href="thread.html#21626">[ thread ]</a>
              <a href="subject.html#21626">[ subject ]</a>
              <a href="author.html#21626">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="DISABLEhttp://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
