<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Freebsd 5.3 - PyThreadState_Delete: tstate is still
	current
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Freebsd%205.3%20-%20PyThreadState_Delete%3A%20tstate%20is%20still%0A%09current&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="017185.html">
   <LINK REL="Next"  HREF="017186.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Freebsd 5.3 - PyThreadState_Delete: tstate is still
	current</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>snacktime</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Freebsd%205.3%20-%20PyThreadState_Delete%3A%20tstate%20is%20still%0A%09current&In-Reply-To="
       TITLE="[mod_python] Freebsd 5.3 - PyThreadState_Delete: tstate is still
	current">snacktime at gmail.com
       </A><BR>
    <I>Sat Jan 22 16:58:44 EST 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="017185.html">[mod_python] Quick question from mod_perl user
</A></li>
        <LI>Next message: <A HREF="017186.html">[mod_python] ANN: Vampire 1.4 is now available.
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17182">[ date ]</a>
              <a href="thread.html#17182">[ thread ]</a>
              <a href="subject.html#17182">[ subject ]</a>
              <a href="author.html#17182">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Freebsd 5.3-p2.  Python 2.4/mod_python 3.1.3 built from ports with
threading disabled (as per mod_python port requirement).


On some requests I get this error message:

Fatal Python error: PyThreadState_Delete: tstate is still current
[Sat Jan 22 21:47:12 2005] [notice] child pid 46205 exit signal Abort trap (6)


For example, with the following in httpd.conf:

&lt;Directory /usr/local/www/data/python&gt;
    SetHandler mod_python
  PythonHandler mod_python.publisher
  PythonDebug On
  &lt;/Directory&gt;

The example index.py from the docs works when the url is
/python/index.  But I get the error with /python/index/hello, or
/python/index/anything_else.

The sample from section 3.3 of the docs does work.  When I tried using
a Location directive instead of Directory, I get the error.

Is something trying to use threads when it's not supposed to?  At
first I thought maybe I had built python with threads, but after
reinstalling python and mod_python without threads I still get the
same errors.

Any ideas?

Chris
</PRE>





<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="017185.html">[mod_python] Quick question from mod_perl user
</A></li>
	<LI>Next message: <A HREF="017186.html">[mod_python] ANN: Vampire 1.4 is now available.
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17182">[ date ]</a>
              <a href="thread.html#17182">[ thread ]</a>
              <a href="subject.html#17182">[ subject ]</a>
              <a href="author.html#17182">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
