<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Newbie Connection Problems
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Newbie%20Connection%20Problems&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="018595.html">
   <LINK REL="Next"  HREF="018605.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Newbie Connection Problems</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Joshua Cohen</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Newbie%20Connection%20Problems&In-Reply-To="
       TITLE="[mod_python] Newbie Connection Problems">JoshC at usracmfg.com
       </A><BR>
    <I>Tue Jul  5 08:47:18 EDT 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="018595.html">[mod_python] Where to get latest sources of mod_python?
</A></li>
        <LI>Next message: <A HREF="018605.html">[mod_python] file() constructor not accessible in restricted mode
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18602">[ date ]</a>
              <a href="thread.html#18602">[ thread ]</a>
              <a href="subject.html#18602">[ subject ]</a>
              <a href="author.html#18602">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Johnathan, 

Thanks for the help. It was indeed SELinux that was causing the problem. Once I disabled it, the connection worked as it should. 

Thanks Again, 

Josh

-----Original Message-----
From: Johnathan Gurley [mailto:<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">johnathan.gurley at gmail.com</A>]
Sent: Saturday, July 02, 2005 2:40 PM
To: Joshua Cohen
Subject: Re: [mod_python] Newbie Connection Problems


Greetings,

Error code 13 is &quot;Permission denied&quot;, so you might want to try
checking the permissions of the user that is running apache.  Also,
most people who are using Fedora report that they have a lot of
general software problems due to the default permission settings of
SELinux.  If you haven't already, try disabling it and see if the
connection goes through.  I hope this helps.

Regards,


Johnathan Gurley

On 7/1/05, Joshua Cohen &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">JoshC at usracmfg.com</A>&gt; wrote:
&gt;<i> Hi Everyone,
</I>&gt;<i> 
</I>&gt;<i> I have been programming in Python for a while now but am new to the mod_python module. I am having problems connecting to a MySQL database using MySQLdb. The database is 4.0.24 and is located on a Windows 2000 server. I am running a Fedora Core 4 PC with Apache 2/Python2.4.1 I have no issues with running a simple test script against mod_python in Apache, all is well. However, when I try to import MySQLdb and create a simple database connection I receive an error
</I>&gt;<i> 
</I>&gt;<i> OperationalError: (2003, &quot;Can't connect to MySQL server on 'IPADDRESSHIDDEN' (13)&quot;)
</I>&gt;<i> 
</I>&gt;<i> The code is very simple and is as follows:
</I>&gt;<i> 
</I>&gt;<i> import MySQLdb
</I>&gt;<i> 
</I>&gt;<i> def sql():
</I>&gt;<i>      db_connection = MySQLdb.connect(host=&quot;IPADDRESS&quot;, user=&quot;user&quot;, passwd=&quot;password&quot;, db=&quot;database&quot;, port=3306)
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> There is no reason for me to go further with the code since I cannot even establish an connection to the DB. If I execute the same basic lines through a prompt, I am able to connect to the DB and query without any issues.
</I>&gt;<i> 
</I>&gt;<i> Any ideas what is going wrong? I've waisted away enough of my life searching google for a solution.
</I>&gt;<i> 
</I>&gt;<i> Thanks,
</I>&gt;<i> 
</I>&gt;<i> Josh
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mod_python mailing list
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">http://mailman.modpython.org/mailman/listinfo/mod_python</A>
</I>&gt;<i>
</I>
</PRE>




<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="018595.html">[mod_python] Where to get latest sources of mod_python?
</A></li>
	<LI>Next message: <A HREF="018605.html">[mod_python] file() constructor not accessible in restricted mode
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18602">[ date ]</a>
              <a href="thread.html#18602">[ thread ]</a>
              <a href="subject.html#18602">[ subject ]</a>
              <a href="author.html#18602">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
