<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] AttributeError: 'mp_request' object has no attribute
	'ssl_var_lookup'
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20AttributeError%3A%20%27mp_request%27%20object%20has%20no%20attribute%0A%09%27ssl_var_lookup%27&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="025278.html">
   <LINK REL="Next"  HREF="025280.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] AttributeError: 'mp_request' object has no attribute
	'ssl_var_lookup'</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Rich Fought</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20AttributeError%3A%20%27mp_request%27%20object%20has%20no%20attribute%0A%09%27ssl_var_lookup%27&In-Reply-To="
       TITLE="[mod_python] AttributeError: 'mp_request' object has no attribute
	'ssl_var_lookup'">whatever at fsrz.net
       </A><BR>
    <I>Wed May 14 20:42:05 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="025278.html">[mod_python] how to use mod_python once the initial test is done
</A></li>
        <LI>Next message: <A HREF="025280.html">[mod_python] AttributeError: 'mp_request' object has no attribute
	'ssl_var_lookup'
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25279">[ date ]</a>
              <a href="thread.html#25279">[ thread ]</a>
              <a href="subject.html#25279">[ subject ]</a>
              <a href="author.html#25279">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I'm migrating a functioning mod_python handler from Windows (Apache 2.0.63, Python 2.3) to
CentOS 5.1 (Apache 2.2.3, Python 2.4) and am getting a very strange error:

Mod_python error: &quot;PythonFixupHandler myHandler&quot;
Traceback (most recent call last):
  File &quot;/usr/lib/python2.4/site-packages/mod_python/apache.py&quot;, line 299, in HandlerDispatch
    result = object(req)

  File &quot;/var/www/mypy/myHandler.py&quot;, line 16, in fixuphandler
    ssl_client_dn = req.ssl_var_lookup('SSL_CLIENT_S_DN')

AttributeError: 'mp_request' object has no attribute 'ssl_var_lookup'

I've been searching all afternoon and my Google-fu has failed me.  I haven't been able to determine
why on the CentOS platform the request object suddenly has no ssl_var_lookup attribute.

Any help would be appreciated,

Thanks,
Rich

</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="025278.html">[mod_python] how to use mod_python once the initial test is done
</A></li>
	<LI>Next message: <A HREF="025280.html">[mod_python] AttributeError: 'mp_request' object has no attribute
	'ssl_var_lookup'
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25279">[ date ]</a>
              <a href="thread.html#25279">[ thread ]</a>
              <a href="subject.html#25279">[ subject ]</a>
              <a href="author.html#25279">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
