<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] Problems with ZODB / modpython
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Problems%20with%20ZODB%20/%20modpython&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="023092.html">
   <LINK REL="Next"  HREF="023039.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] Problems with ZODB / modpython</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Graham Dumpleton</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20Problems%20with%20ZODB%20/%20modpython&In-Reply-To="
       TITLE="[mod_python] Problems with ZODB / modpython">grahamd at dscpl.com.au
       </A><BR>
    <I>Wed Jan 17 15:53:00 EST 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="023092.html">[mod_python] how to handle xforms with publisher handler
</A></li>
        <LI>Next message: <A HREF="023039.html">[mod_python] Problems with ZODB / modpython
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23037">[ date ]</a>
              <a href="thread.html#23037">[ thread ]</a>
              <a href="subject.html#23037">[ subject ]</a>
              <a href="author.html#23037">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Thiago Comicio wrote ..
&gt;<i> Hi,
</I>&gt;<i> 
</I>&gt;<i> I'm trying to install a program that needs mod_python and ZODB. The
</I>&gt;<i> program is not running, so I tried to connect to the database through
</I>&gt;<i> this script:
</I>&gt;<i> 
</I>&gt;<i> from ZODB import FileStorage, DB
</I>&gt;<i> 
</I>&gt;<i> def index(req, **params):
</I>&gt;<i>         storage = FileStorage.FileStorage('mydatabase.fs')
</I>&gt;<i>         db = DB(storage)
</I>&gt;<i>         connection = db.open()
</I>&gt;<i>         root = connection.root()
</I>&gt;<i>         return TestPage().getHTML()
</I>&gt;<i> 
</I>&gt;<i> And I received the error below.
</I>&gt;<i> Does anybody know how to fix it?
</I>
A couple of things to be aware of.

1. The Apache web server generally runs as a special user and thus that user
must have write access to the directory where you are wanting to create the
database.

2. The current working directory is normally '/' for the Apache processes and
thus if you do not specify an absolute path to where you want to store the
database, it will try and store it in '/' where you are unlikely to have permissions
to write. You should not change the working directory as if every handler did
that they would all interfere with each other.

Graham
 
&gt;<i> Thanks
</I>&gt;<i> 
</I>&gt;<i> Thiago
</I>&gt;<i> 
</I>&gt;<i> ---------------------------
</I>&gt;<i> 
</I>&gt;<i> Mod_python error: &quot;PythonHandler mod_python.publisher&quot;
</I>&gt;<i> 
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i> 
</I>&gt;<i>   File &quot;/usr/lib/python2.4/site-packages/mod_python/apache.py&quot;, line
</I>&gt;<i> 299, in HandlerDispatch
</I>&gt;<i>     result = object(req)
</I>&gt;<i> 
</I>&gt;<i>   File &quot;/usr/lib/python2.4/site-packages/mod_python/publisher.py&quot;,
</I>&gt;<i> line 213, in handler
</I>&gt;<i>     published = publish_object(req, object)
</I>&gt;<i> 
</I>&gt;<i>   File &quot;/usr/lib/python2.4/site-packages/mod_python/publisher.py&quot;,
</I>&gt;<i> line 412, in publish_object
</I>&gt;<i>     return publish_object(req,util.apply_fs_data(object, req.form, req=req))
</I>&gt;<i> 
</I>&gt;<i>   File &quot;/usr/lib/python2.4/site-packages/mod_python/util.py&quot;, line
</I>&gt;<i> 439, in apply_fs_data
</I>&gt;<i>     return object(**args)
</I>&gt;<i> 
</I>&gt;<i>   File &quot;/var/www/html/indico/teste.py&quot;, line 4, in index
</I>&gt;<i>     storage = FileStorage.FileStorage('mydatabase.fs')
</I>&gt;<i> 
</I>&gt;<i>   File &quot;/usr/lib/zope/lib/python/ZODB/FileStorage/FileStorage.py&quot;,
</I>&gt;<i> line 112, in __init__
</I>&gt;<i>     self._lock_file = LockFile(file_name + '.lock')
</I>&gt;<i> 
</I>&gt;<i>   File &quot;/usr/lib/zope/lib/python/ZODB/lock_file.py&quot;, line 60, in __init__
</I>&gt;<i>     self._fp = open(path, 'w+')
</I>&gt;<i> 
</I>&gt;<i> IOError: [Errno 13] Permission denied: 'mydatabase.fs.lock'
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mod_python mailing list
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;<i> <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">http://mailman.modpython.org/mailman/listinfo/mod_python</A>
</I></PRE>




<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="023092.html">[mod_python] how to handle xforms with publisher handler
</A></li>
	<LI>Next message: <A HREF="023039.html">[mod_python] Problems with ZODB / modpython
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23037">[ date ]</a>
              <a href="thread.html#23037">[ thread ]</a>
              <a href="subject.html#23037">[ subject ]</a>
              <a href="author.html#23037">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42971867-2', 'modpython.org');
  ga('send', 'pageview');
</script>

</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
