<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] weird error in mod_python (3.1.4.r1)
	/scipy(0.4.8)/gentoo (~x86) web application
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20weird%20error%20in%20mod_python%20%283.1.4.r1%29%0A%09/scipy%280.4.8%29/gentoo%20%28%7Ex86%29%20web%20application&In-Reply-To=1144035392.2357%40dscpl.user.openhosting.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="020746.html">
   <LINK REL="Next"  HREF="020748.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[mod_python] weird error in mod_python (3.1.4.r1)
	/scipy(0.4.8)/gentoo (~x86) web application</H1>
<table border=0 width="100%"><tr><td valign="top">
    <B>Webb Sprague</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20weird%20error%20in%20mod_python%20%283.1.4.r1%29%0A%09/scipy%280.4.8%29/gentoo%20%28%7Ex86%29%20web%20application&In-Reply-To=1144035392.2357%40dscpl.user.openhosting.com"
       TITLE="[mod_python] weird error in mod_python (3.1.4.r1)
	/scipy(0.4.8)/gentoo (~x86) web application">webb.sprague at gmail.com
       </A><BR>
    <I>Mon Apr  3 00:06:16 EDT 2006</I>
    <P><UL>
        <LI>Previous message: <A HREF="020746.html">[mod_python] weird error in mod_python (3.1.4.r1)
	/scipy(0.4.8)/gentoo (~x86) web application
</A></li>
        <LI>Next message: <A HREF="020748.html">[mod_python] Pickled objects require _apache on un-pickling
	(mod_python 3.2.8)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#20747">[ date ]</a>
              <a href="thread.html#20747">[ thread ]</a>
              <a href="subject.html#20747">[ subject ]</a>
              <a href="author.html#20747">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Thanks to Graham's help, I found the typo
(&quot;sys.path.append(os.getcwd)&quot; should have been
&quot;sys.path.append(os.getcwd())&quot;), and all is well.

W

On 4/2/06, Graham Dumpleton &lt;<A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">grahamd at dscpl.com.au</A>&gt; wrote:
&gt;<i> Webb Sprague wrote ..
</I>&gt;<i> &gt; This may be un-reproducible, and it does NOT happen within ipython
</I>&gt;<i> &gt; shell, but I am getting the backtrace below when trying to import
</I>&gt;<i> &gt; scipy within my application.  I would guess it has to do with the very
</I>&gt;<i> &gt; outdated ebuild of mod_python, (see the gentoo bug:
</I>&gt;<i> &gt; <A HREF="http://bugs.gentoo.org/show_bug.cgi?id=123852">http://bugs.gentoo.org/show_bug.cgi?id=123852</A>), but just in case
</I>&gt;<i> &gt; anybody has any quick fixes, please let me know.
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; I have restarted Apache numerous times to make sure there isn't some
</I>&gt;<i> &gt; weird cache thing going on (the source of most of my phantom bug
</I>&gt;<i> &gt; reports).  Scipy 0.3.2 does not have this problem.
</I>&gt;<i>
</I>&gt;<i> Looking through pkg_resources.py, critical bit of code seems to be:
</I>&gt;<i>
</I>&gt;<i> class WorkingSet(object):
</I>&gt;<i>     &quot;&quot;&quot;A collection of active distributions on sys.path (or a similar list)&quot;&quot;&quot;
</I>&gt;<i>
</I>&gt;<i>     def __init__(self, entries=None):
</I>&gt;<i>         &quot;&quot;&quot;Create working set from list of path entries (default=sys.path)&quot;&quot;&quot;
</I>&gt;<i>         self.entries = []
</I>&gt;<i>         self.entry_keys = {}
</I>&gt;<i>         self.by_key = {}
</I>&gt;<i>         self.callbacks = []
</I>&gt;<i>
</I>&gt;<i>         if entries is None:
</I>&gt;<i>             entries = sys.path
</I>&gt;<i>
</I>&gt;<i>         for entry in entries:
</I>&gt;<i>             self.add_entry(entry)
</I>&gt;<i>
</I>&gt;<i> Specifically, &quot;entries&quot; is set to 'sys.path' and then each entry in that is
</I>&gt;<i> processed. The final error suggests that one of the entries in 'sys.path'
</I>&gt;<i> is actually a function and not a string.
</I>&gt;<i>
</I>&gt;<i> Are you setting 'sys.path' using PythonPath directive in mod_python
</I>&gt;<i> and somehow stuffed it up, or are you setting 'sys.path' explicitly in
</I>&gt;<i> any other places?
</I>&gt;<i>
</I>&gt;<i> Graham
</I>&gt;<i>
</I>&gt;<i> &gt; Backtrace follows. (6), with LcUtil.py, is where it tries to import
</I>&gt;<i> &gt; and errors out.
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; Mod_python error: &quot;PythonHandler mod_python.publisher&quot;
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; Traceback (most recent call last):
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; (1)  File &quot;/usr/lib/python2.4/site-packages/mod_python/apache.py&quot;,
</I>&gt;<i> &gt; line 299, in HandlerDispatch
</I>&gt;<i> &gt;     result = object(req)
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; (2)  File &quot;/usr/lib/python2.4/site-packages/mod_python/publisher.py&quot;,
</I>&gt;<i> &gt; line 98, in handler
</I>&gt;<i> &gt;     path=[path])
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; (3)  File &quot;/usr/lib/python2.4/site-packages/mod_python/apache.py&quot;,
</I>&gt;<i> &gt; line 457, in import_module
</I>&gt;<i> &gt;     module = imp.load_module(mname, f, p, d)
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; (4)  File &quot;/var/www/localhost/htdocs/larry/lc.py&quot;, line 32, in ?
</I>&gt;<i> &gt;     import LcSinglePopObject
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;  (5) File &quot;/var/www/localhost/htdocs/larry/LcSinglePopObject.py&quot;, line
</I>&gt;<i> &gt; 40, in ?
</I>&gt;<i> &gt;     import LcUtil
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; (6)  File &quot;/var/www/localhost/htdocs/larry/LcUtil.py&quot;, line 8, in ?
</I>&gt;<i> &gt;     import scipy as S
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;   File &quot;/usr/lib/python2.4/site-packages/scipy/__init__.py&quot;, line 18, in
</I>&gt;<i> &gt; ?
</I>&gt;<i> &gt;     import pkg_resources as _pr # activate namespace packages
</I>&gt;<i> &gt; (manipulates __path__)
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;   File &quot;/usr/lib/python2.4/site-packages/pkg_resources.py&quot;, line 2347,
</I>&gt;<i> &gt; in ?
</I>&gt;<i> &gt;     working_set = WorkingSet()
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;   File &quot;/usr/lib/python2.4/site-packages/pkg_resources.py&quot;, line 343,
</I>&gt;<i> &gt; in __init__
</I>&gt;<i> &gt;     self.add_entry(entry)
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;   File &quot;/usr/lib/python2.4/site-packages/pkg_resources.py&quot;, line 358,
</I>&gt;<i> &gt; in add_entry
</I>&gt;<i> &gt;     for dist in find_distributions(entry, True):
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;   File &quot;/usr/lib/python2.4/site-packages/pkg_resources.py&quot;, line 1450,
</I>&gt;<i> &gt; in find_distributions
</I>&gt;<i> &gt;     importer = get_importer(path_item)
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;   File &quot;/usr/lib/python2.4/site-packages/pkg_resources.py&quot;, line 1407,
</I>&gt;<i> &gt; in get_importer
</I>&gt;<i> &gt;     importer = hook(path_item)
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; TypeError: zipimporter() argument 1 must be string, not
</I>&gt;<i> &gt; builtin_function_or_method
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; _______________________________________________
</I>&gt;<i> &gt; Mod_python mailing list
</I>&gt;<i> &gt; <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">Mod_python at modpython.org</A>
</I>&gt;<i> &gt; <A HREF="http://mailman.modpython.org/mailman/listinfo/mod_python">http://mailman.modpython.org/mailman/listinfo/mod_python</A>
</I>&gt;<i>
</I>
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="020746.html">[mod_python] weird error in mod_python (3.1.4.r1)
	/scipy(0.4.8)/gentoo (~x86) web application
</A></li>
	<LI>Next message: <A HREF="020748.html">[mod_python] Pickled objects require _apache on un-pickling
	(mod_python 3.2.8)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#20747">[ date ]</a>
              <a href="thread.html#20747">[ thread ]</a>
              <a href="subject.html#20747">[ subject ]</a>
              <a href="author.html#20747">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="DISABLEhttp://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
