<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [mod_python] mod_python 3.0.1: error after make install
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%203.0.1%3A%20error%20after%20make%20install&In-Reply-To=002001c2a021%2466b50720%241c291a97%40sorpippo">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="009570.html">
   <LINK REL="Next"  HREF="009576.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
<table border=0 width="100%"><tr><td valign="top">
   <H1>[mod_python] mod_python 3.0.1: error after make install</H1>
    <B>bvr</B> 
    <A HREF="mailto:mod_python%40modpython.org?Subject=%5Bmod_python%5D%20mod_python%203.0.1%3A%20error%20after%20make%20install&In-Reply-To=002001c2a021%2466b50720%241c291a97%40sorpippo"
       TITLE="[mod_python] mod_python 3.0.1: error after make install">listmail at xs4all.nl
       </A><BR>
    <I>Thu Dec 12 22:30:15 EST 2002</I>
    <P><UL>
        <LI>Previous message: <A HREF="009570.html">[mod_python] mod_python 3.0.1: error after make install ---&gt;
 Debian
</A></li>
        <LI>Next message: <A HREF="009576.html">[mod_python] mod_python 3.0.1: error after make install
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9575">[ date ]</a>
              <a href="thread.html#9575">[ thread ]</a>
              <a href="subject.html#9575">[ subject ]</a>
              <a href="author.html#9575">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

Same problem here, tried several installations with RH 7.3.

tried installing these:
python2-2.2-16.i386.rpm
python2-devel-2.2-16.i386.rpm
python2-docs-2.2-16.i386.rpm

and:
untar Python-2.2.2.tgz
configure --without-threads
make &amp;&amp; make install

both with no errors, cli interpreter works fine

compiled mod python 3.0.1 like this:

configure --with-apxs=/usr/local/apache2/bin/apxs 
--with-python=/usr/local/bin/python2
make

everything looks fine untill I get these warnings at the end:

/usr/local/apache/build/libtool --silent --mode=link gcc -o 
mod_python.la -I/store/install/mod_python-3.0.1/src/include 
-I/usr/local/apache/include -I/usr/local/include/python2.2  -rpath 
/usr/local/apache/modules -module -avoid-version  hlistobject.lo 
hlist.lo filterobject.lo connobject.lo serverobject.lo util.lo 
tableobject.lo requestobject.lo _apachemodule.lo mod_python.lo 
-L/usr/local/lib/python2.2/config -Xlinker -export-dynamic -lm 
-lpython2.2 -ldl -lutil -lm

*** Warning: This library needs some functionality provided by -lpython2.2.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have.

*** Warning: libtool could not satisfy all declared inter-library
*** dependencies of module mod_python.  Therefore, libtool will create
*** a static module, that should work as long as the dlopening
*** application is linked with the -dlopen flag.

afterwards it appears src/mod_python.so has not been created.

my best guess is that i need a libpython2.2.so but i can't figure how
to get it ??


please help!

bvr.


Zoper wrote:
&gt;<i> Hi All!
</I>&gt;<i> 
</I>&gt;<i> After making my mod_python I try to make install but...
</I>&gt;<i> 
</I>&gt;<i> ...............CUT....................
</I>&gt;<i> Performing DSO installation.
</I>&gt;<i> 
</I>&gt;<i> /usr/bin/install -c src/mod_python.so /usr/local/apache2/modules
</I>&gt;<i> /usr/bin/install: src/mod_python.so: No such file or directory
</I>&gt;<i> make[1]: *** [install_dso] Error 1
</I>&gt;<i> make[1]: Leaving directory `/usr/src/mod_python-3.0.1'
</I>&gt;<i> make: *** [install] Error 2
</I>&gt;<i> ..........................................
</I>

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="009570.html">[mod_python] mod_python 3.0.1: error after make install ---&gt;
 Debian
</A></li>
	<LI>Next message: <A HREF="009576.html">[mod_python] mod_python 3.0.1: error after make install
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9575">[ date ]</a>
              <a href="thread.html#9575">[ thread ]</a>
              <a href="subject.html#9575">[ subject ]</a>
              <a href="author.html#9575">[ author ]</a>
         </LI>
       </UL>

</td>
<td align="right" valign="top">
<script type="text/javascript"><!--
google_ad_client = "pub-9718360309690383";
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_color_border = "CCCCCC";
google_color_bg = "FFFFFF";
google_color_link = "000000";
google_color_url = "666666";
google_color_text = "333333";
//--></script>
<script type="text/javascript"
  src="DISABLEhttp://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</td>
</table>

<hr>
<a href="http://mailman.modpython.org/mailman/listinfo/mod_python">More information about the Mod_python
mailing list</a><br>
</body></html>
